import { NextRequest, NextResponse } from "next/server";

export const runtime = "nodejs";

interface SupportRequestBody {
  firstName?: string;
  lastName?: string;
  email?: string;
  description?: string;
  videoLink?: string;
  relatedPageLink?: string;
  otherDetails?: string;
  files?: string[];
  chatSessionId?: string;
  threadId?: string;
  conversationId?: string;
  conversationLink?: string;
  isConversationRequest?: boolean;
}

export async function POST(request: NextRequest) {
  try {
    const body: SupportRequestBody = await request.json();

    // Validate required fields based on form type
    if (body.isConversationRequest) {
      // Conversation form doesn't require name/email
    } else {
      // Full form requires name and email
      if (!body.firstName || !body.lastName || !body.email) {
        return NextResponse.json(
          { error: "Missing required fields: firstName, lastName, email" },
          { status: 400 }
        );
      }
    }

    // Get Zapier webhook URL from environment variable
    // Support separate webhooks for conversation requests vs full form requests
    const zapierWebhookUrl = body.isConversationRequest
      ? (process.env.ZAPIER_CONVERSATION_WEBHOOK_URL || process.env.ZAPIER_WEBHOOK_URL)
      : (process.env.ZAPIER_FULL_FORM_WEBHOOK_URL || process.env.ZAPIER_WEBHOOK_URL);
    
    if (!zapierWebhookUrl) {
      const missingVar = body.isConversationRequest
        ? "ZAPIER_CONVERSATION_WEBHOOK_URL or ZAPIER_WEBHOOK_URL"
        : "ZAPIER_FULL_FORM_WEBHOOK_URL or ZAPIER_WEBHOOK_URL";
      console.error(`[submit-support-request] ${missingVar} not configured`);
      return NextResponse.json(
        { 
          error: "Webhook URL not configured",
          details: `Please set ${missingVar} environment variable in AWS Amplify`
        },
        { status: 500 }
      );
    }

    // Prepare data for Zapier webhook
    // Map to new table structure with headers:
    // modified-date, created-date, first-name, last-name, user-email, video-link, upload-files,
    // link-url, user-subscription-plan, user-admin-status, ticket-subject, ticket-description,
    // extra-details, transcript, transcript-summary, chatbot-session-id, use-conversation,
    // conversation-link, thread-id, date, Status, ticket-id
    
    const now = new Date().toISOString();
    const dateOnly = new Date().toISOString().split('T')[0]; // YYYY-MM-DD format
    
    const zapierData: Record<string, unknown> = {
      // Date fields
      "created-date": now,
      "modified-date": now,
      "date": dateOnly,
      
      // Conversation metadata
      "chatbot-session-id": body.chatSessionId || "",
      "thread-id": body.threadId || "",
      "conversation-link": body.conversationLink || "",
      "use-conversation": body.isConversationRequest || false,
      
      // Transcript fields (populated by Zapier automation triggered by new rows)
      "transcript": "",
      "transcript-summary": "",
      
      // User metadata (populated by Zapier automation if user data is available)
      "user-subscription-plan": "",
      "user-admin-status": "",
      
      // Status (set by Zapier automation/workflow)
      "Status": "",
      
      // Ticket ID (generated by Zapier automation)
      "ticket-id": "",
      
      // Ticket subject (set by Zapier automation triggered by new rows)
      "ticket-subject": "",
    };

    if (body.isConversationRequest) {
      // Conversation form fields - minimal data since context comes from conversation
      zapierData["first-name"] = "";
      zapierData["last-name"] = "";
      zapierData["user-email"] = "";
      zapierData["video-link"] = body.videoLink || "";
      zapierData["upload-files"] = Array.isArray(body.files) ? body.files.join(", ") : (body.files || "");
      zapierData["link-url"] = "";
      zapierData["ticket-description"] = "";
      zapierData["extra-details"] = body.otherDetails || "";
    } else {
      // Full form fields - complete user information
      zapierData["first-name"] = body.firstName || "";
      zapierData["last-name"] = body.lastName || "";
      zapierData["user-email"] = body.email || "";
      zapierData["video-link"] = body.videoLink || "";
      zapierData["upload-files"] = Array.isArray(body.files) ? body.files.join(", ") : (body.files || "");
      zapierData["link-url"] = body.relatedPageLink || "";
      zapierData["ticket-description"] = body.description || "";
      zapierData["extra-details"] = "";
    }

    // Log the data being sent (for debugging)
    console.log("[submit-support-request] Sending data to Zapier:", JSON.stringify(zapierData, null, 2));
    
    // Send to Zapier webhook
    const response = await fetch(zapierWebhookUrl, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(zapierData),
    });

    if (!response.ok) {
      const errorText = await response.text().catch(() => "Unknown error");
      console.error("[submit-support-request] Zapier webhook error:", response.status, errorText);
      return NextResponse.json(
        { error: `Failed to submit to Zapier: ${response.status}` },
        { status: 500 }
      );
    }

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error("[submit-support-request] Error:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}

