AWSTemplateFormatVersion: '2010-09-09'
Description: 'Simple CloudFront distribution for ChatKit (no Lambda@Edge)'

Resources:
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          TargetOriginId: us-east-1-origin
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
          OriginRequestPolicyId: acba4595-bd28-49b8-b9fe-13317c0390fa
          AllowedMethods: [DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT]
          CachedMethods: [GET, HEAD]
        CacheBehaviors:
          - PathPattern: "api/*"
            TargetOriginId: us-east-1-origin
            ViewerProtocolPolicy: redirect-to-https
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
            OriginRequestPolicyId: acba4595-bd28-49b8-b9fe-13317c0390fa
            AllowedMethods: [DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT]
            CachedMethods: [GET, HEAD]
        Origins:
          - Id: us-east-1-origin
            DomainName: main.d2xcz3k9ugtvab.amplifyapp.com
            CustomOriginConfig:
              HTTPPort: 443
              OriginProtocolPolicy: https-only
        Enabled: true
        HttpVersion: http2
        PriceClass: PriceClass_All

Outputs:
  CloudFrontURL:
    Description: 'CloudFront URL'
    Value: !Sub 'https://${CloudFrontDistribution.DomainName}'