AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFront distribution with Lambda@Edge for ChatKit global routing'

Parameters:
  DomainName:
    Type: String
    Description: 'Your custom domain name (e.g., chat.yourdomain.com)'
    Default: 'your-domain.com'
  
  CertificateArn:
    Type: String
    Description: 'ACM certificate ARN for your domain (must be in us-east-1)'

Resources:
  LambdaEdgeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - edgelambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  RoutingFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: chatkit-geographic-routing
      Runtime: nodejs18.x
      Handler: index.handler
      Role: !GetAtt LambdaEdgeRole.Arn
      Code:
        ZipFile: |
          exports.handler = (event, context, callback) => {
              const request = event.Records[0].cf.request;
              const headers = request.headers;
              
              const country = headers['cloudfront-viewer-country'] 
                  ? headers['cloudfront-viewer-country'][0].value 
                  : 'US';
              
              const apacCountries = ['AU', 'NZ'];
              const useApac = apacCountries.includes(country);
              
              request.origin = {
                  custom: {
                      domainName: useApac 
                          ? 'main.d1m1p4jeb6ymp7.amplifyapp.com'
                          : 'main.d2xcz3k9ugtvab.amplifyapp.com',
                      port: 443,
                      protocol: 'https',
                      path: ''
                  }
              };
              
              callback(null, request);
          };

  RoutingFunctionVersion:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref RoutingFunction

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref DomainName
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        DefaultCacheBehavior:
          TargetOriginId: primary-origin
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad  # CachingDisabled
          OriginRequestPolicyId: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf  # CORS-S3Origin
          LambdaFunctionAssociations:
            - EventType: origin-request
              LambdaFunctionARN: !Ref RoutingFunctionVersion
        Origins:
          - Id: primary-origin
            DomainName: main.d2xcz3k9ugtvab.amplifyapp.com
            CustomOriginConfig:
              HTTPPort: 443
              OriginProtocolPolicy: https-only
        Enabled: true
        HttpVersion: http2
        PriceClass: PriceClass_All

Outputs:
  CloudFrontDomainName:
    Description: 'CloudFront distribution domain name'
    Value: !GetAtt CloudFrontDistribution.DomainName
  
  DistributionId:
    Description: 'CloudFront distribution ID'
    Value: !Ref CloudFrontDistribution