AWSTemplateFormatVersion: '2010-09-09'
Description: 'Route 53 geographic routing for ChatKit'

Parameters:
  DomainName:
    Type: String
    Description: 'Your domain name (e.g., chat.yourdomain.com)'

Resources:
  # CloudFront for APAC region
  APACCloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          TargetOriginId: apac-origin
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
          OriginRequestPolicyId: acba4595-bd28-49b8-b9fe-13317c0390fa
          AllowedMethods: [DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT]
          CachedMethods: [GET, HEAD]
        CacheBehaviors:
          - PathPattern: "api/*"
            TargetOriginId: apac-origin
            ViewerProtocolPolicy: redirect-to-https
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
            OriginRequestPolicyId: acba4595-bd28-49b8-b9fe-13317c0390fa
            AllowedMethods: [DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT]
            CachedMethods: [GET, HEAD]
        Origins:
          - Id: apac-origin
            DomainName: main.d1m1p4jeb6ymp7.amplifyapp.com
            CustomOriginConfig:
              HTTPPort: 443
              OriginProtocolPolicy: https-only
        Enabled: true
        HttpVersion: http2
        PriceClass: PriceClass_All

  # Route 53 Records
  APACRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub '${DomainName}.'
      Name: !Ref DomainName
      Type: A
      SetIdentifier: 'APAC'
      Geolocation:
        ContinentCode: 'OC'
      AliasTarget:
        DNSName: !GetAtt APACCloudFront.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

  DefaultRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub '${DomainName}.'
      Name: !Ref DomainName
      Type: A
      SetIdentifier: 'Default'
      Geolocation:
        CountryCode: '*'
      AliasTarget:
        DNSName: d4riwmslfvqxw.cloudfront.net
        HostedZoneId: Z2FDTNDATAQYW2

Outputs:
  APACCloudFrontURL:
    Description: 'APAC CloudFront URL'
    Value: !Sub 'https://${APACCloudFront.DomainName}'